
export const GET_COUNTRIES_RELEGION_ATTEMPING = 'GET_COUNTRIES_RELEGION_ATTEMPING';
export const GET_COUNTRIES_RELEGION_SUCCESS   = 'GET_COUNTRIES_RELEGION_SUCCESS';
export const GET_COUNTRIES_RELEGION_FAILED    = 'GET_COUNTRIES_RELEGION_FAILED';

export const SAVE_NEW_USER_ATTEMPING = 'SAVE_NEW_USER_ATTEMPING';
export const SAVE_NEW_USER_SUCCESS   = 'SAVE_NEW_USER_SUCCESS';
export const SAVE_NEW_USER_FAILED    = 'SAVE_NEW_USER_FAILED';


export const GET_QUESTIONS_ATTEMPING = 'GET_QUESTIONS_ATTEMPING';
export const GET_QUESTIONS_SUCCESS   = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILED    = 'GET_QUESTIONS_FAILED';


export const QUIZ_ANSWER_ATTEMPING = 'QUIZ_ANSWER_ATTEMPING';
export const QUIZ_ANSWER_SUCCESS   = 'QUIZ_ANSWER_SUCCESS';
export const QUIZ_ANSWER_FAILED    = 'QUIZ_ANSWER_FAILED';


export const QUIZ_RESULT_ATTEMPING = 'QUIZ_RESULT_ATTEMPING';
export const QUIZ_RESULT_SUCCESS   = 'QUIZ_RESULT_SUCCESS';
export const QUIZ_RESULT_FAILED    = 'QUIZ_RESULT_FAILED';


export const SIGNUP_ATTEMPING = 'SIGNUP_ATTEMPING';
export const SIGNUP_SUCCESS   = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED    = 'SIGNUP_FAILED';


export const LOGIN_ATTEMPING = 'LOGIN_ATTEMPING';
export const LOGIN_SUCCESS   = 'LOGIN_SUCCESS';
export const LOGIN_FAILED    = 'LOGIN_FAILED';

